'use strict';
// 在另一个文件中引用moudle
angular.module('app').config(['$stateProvider','$urlRouterProvider',
	function($stateProvider,$urlRouterProvider){
		$stateProvider.state('main',{
			url:'/main',
			templateUrl:'view/main.html',
			controller:'mainCtrl'
		}).state('position',{
			url:'/position/:id',
			templateUrl:'view/position.html',
			controller:'positionCtrl'
		}).state('companyInfo',{
			url:'/companyInfo/:id',
			templateUrl:'view/company_info.html',
			controller:'companyinfoCtrl'
		}).state('search',{
			url:'/search',
			templateUrl:'view/search.html',
			controller:'searchCtrl'
		}).state('login',{
			url:'/login',
			templateUrl:'view/login.html',
			controller:'loginCtrl'
		}).state('register',{
			url:'/register',
			templateUrl:'view/register.html',
			controller:'registerCtrl'
		}).state('collection',{
			url:'/collection',
			templateUrl:'view/collection.html',
			controller:'collectionCtrl'
		}).state('self',{
			url:'/self',
			templateUrl:'view/self.html',
			controller:'selfCtrl'
		}).state('postLog',{
			url:'/postLog',
			templateUrl:'view/postLog.html',
			controller:'postLogCtrl'
		});
		$urlRouterProvider.otherwise('main');
}])